server:
  port: 8082

spring:
  application:
    name: telecom-service

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

telecom:
  success-rate: 85
  processing-delay: true  # Simulate processing delays

logging:
  level:
    com.telecom: INFO
    org.springframework: WARN

