version: '3.8'
services:
  postgres:
    container_name: postgres
    image: 'postgres:16'
    hostname: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    command:
      - postgres
      - '-c'
      - max_connections=500
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: 'bitnami/kafka:3.7'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_CFG_LISTENERS=PLAINTEXT://:9092'
      - 'KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092'
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka-data:/bitnami/kafka'
volumes:
  postgres-data: null
  kafka-data: null
